ALTER TABLE assignees ADD COLUMN birthday TEXT;
ALTER TABLE assignees ADD COLUMN department TEXT NOT NULL DEFAULT '';
ALTER TABLE assignees ADD COLUMN role TEXT NOT NULL DEFAULT '';
ALTER TABLE assignees ADD COLUMN timezone TEXT NOT NULL DEFAULT '';
ALTER TABLE assignees ADD COLUMN interests TEXT NOT NULL DEFAULT '';
ALTER TABLE assignees ADD COLUMN skills TEXT NOT NULL DEFAULT '';
ALTER TABLE assignees ADD COLUMN work_style TEXT NOT NULL DEFAULT '';
ALTER TABLE assignees ADD COLUMN notes TEXT NOT NULL DEFAULT '';
